# Generated by Django 5.1.7 on 2025-04-29 15:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("CS", "Computer Science"),
                            ("ME", "Mechanical Engineering"),
                            ("EE", "Electrical Engineering"),
                            ("IT", "Information Technology"),
                            ("CE", "Civil Engineering"),
                            ("AE", "Automobile Engineering"),
                            ("MA", "Mathematics"),
                            ("PH", "Physics"),
                            ("CH", "Chemistry"),
                            ("GA", "General Aptitude"),
                            ("OT", "Other"),
                        ],
                        default="OT",
                        max_length=2,
                    ),
                ),
                ("file", models.FileField(upload_to="notes/")),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="PreviousQuestionPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("year", models.PositiveIntegerField()),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("CS", "Computer Science"),
                            ("ME", "Mechanical Engineering"),
                            ("EE", "Electrical Engineering"),
                            ("IT", "Information Technology"),
                            ("CE", "Civil Engineering"),
                            ("AE", "Automobile Engineering"),
                            ("MA", "Mathematics"),
                            ("PH", "Physics"),
                            ("CH", "Chemistry"),
                            ("GA", "General Aptitude"),
                            ("OT", "Other"),
                        ],
                        max_length=2,
                    ),
                ),
                ("file", models.FileField(upload_to="previous_papers/")),
                (
                    "uploaded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_papers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "subject"],
            },
        ),
    ]
