# Generated by Django 5.1.7 on 2025-04-29 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exam", "0002_note_previousquestionpaper"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="proctorlog",
            options={"ordering": ["timestamp"]},
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="is_phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="otp_session_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="candidateprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="question",
            name="marks",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="question",
            name="negative_marks",
            field=models.FloatField(default=0.33),
        ),
        migrations.AlterField(
            model_name="candidateprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="candidateprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
